### ISSUE TITLE
Distance not according to Strava

### ISSUE THREAD

**Issue by Flo-ris** [mvan231/Scriptable#1]
The distance in the widget is not the same as it is on Strava profile. I can compare on bikeing and running. Running has a deviation of 900km and biking 500km. Is there a difference between public and private activities in the API?

**Comment by mvan231** [comment]
Thanks for the info about this. I just looked in the API documentation and it states this:

> Get Athlete Stats (getStats)
Returns the activity stats of an athlete. **Only includes data from activities set to Everyone visibilty**

Based on this note about the Get Athlete Stats endPoint, I can say yes, there is a difference. 
There is a way I could sum up all the activities manually that get returned. However, it also has a restriction for the "only me" tag unless using the read_all activity token

> List Athlete Activities (getLoggedInAthleteActivities)
Returns the activities of an athlete for a specific identifier. Requires activity:read. **Only Me activities will be filtered out unless requested by a token with activity:read_all.**

**Comment by mvan231** [comment]
Based on the strava API documents, displaying the private activities could be possible but would require some different API calls to be made and would need some additional authorization. Are you okay if I close this issue?
