### ISSUE TITLE
Change

### ISSUE THREAD

**Issue by usher2005** [mvan231/Scriptable#12]
How do I add a username

**Comment by mvan231** [comment]
I'm not sure what widget you're talking about. Is this for Twitter Widget? If so, you can see the documentation on the GitHub page for how to set username in the widget parameter

**Comment by usher2005** [comment]
I have looked but can’t seem to change

**Comment by mvan231** [comment]
I'm confused by what you mean. The instructions just state to use the widget settings to set the widget parameter. Did you not see that option there?

**Comment by mvan231** [comment]
I'm going to close this issue. If you still have problems, please comment again here
