### ISSUE TITLE
COVID Trend Widget: 2 word countries problem?

### ISSUE THREAD

**Issue by permaMonk** [mvan231/Scriptable#17]
Any problems with a two word country? As example “South Africa”.

If I set in in line 39:
const country = args.widgetParameter?args.widgetParameter:'South Africa'
i get a:
2021-12-05 14:35:08: Error: The URL is invalid.
error.

Any one word country work flawless.

**Comment by permaMonk** [comment]
Wrong place

**Comment by permaMonk** [comment]
Maybe not? Idk

**Comment by mvan231** [comment]
Did you put it in the widget parameter as explained in the instructions? You should not have to modify the code itself

**Comment by permaMonk** [comment]
Both. First in widget parameter, later in the code self. Should I delete the widget and start from the beginning?

**Comment by mvan231** [comment]
I've updated the widget code to accommodate country names with spaces better. You can get it to work with "South Africa" now.

**Comment by permaMonk** [comment]
After update it works flawless. Thx for your fast reaction and work. :))

**Comment by mvan231** [comment]
So glad to hear it! Also, thanks for using this widget!!!
