### ISSUE TITLE
COVID Trend Widget. Exception occured: 179:19

### ISSUE THREAD

**Issue by permaMonk** [mvan231/Scriptable#18]
Type error: contents is not an object. (evaluating itemName in contents)

Nothing changed. Nothing edited.

What happened?

**Comment by permaMonk** [comment]
If I make a duplicate, change the country to “Spain” I get the same line/position error in Scriptable but the widget is displayed. Strange 😳

**Comment by permaMonk** [comment]
If I use all these widgets with country name with small starting letters it works. Example: denmark and not Denmark.

**Comment by mvan231** [comment]
> If I use all these widgets with country name with small starting letters it works. Example: denmark and not Denmark.

That is very strange. And this is always happening for you?

**Comment by permaMonk** [comment]
It’s getting worse. Countries with small starting letter: germany, denmark, italy. One normal writing: Spain. Tried many other - the one and only normal resides is Spain.

Delete the widgets and reinstall = nope. Same situation.

**Comment by mvan231** [comment]
> It’s getting worse. Countries with small starting letter: germany, denmark, italy. One normal writing: Spain. Tried many other - the one and only normal resides is Spain.
> 
> Delete the widgets and reinstall = nope. Same situation.

That is, indeed strange. I tried all of those countries with both upper case first letter and lower case and all of them worked without issue. What error are you seeing? Still the same one?

Could you look in iCloud Drive under the scriptable folder then covid widget folder and see what files are there? Seems it's hanging up on the caching of the data for some reason

**Comment by permaMonk** [comment]
Ok, if choose big letters in start of a country I get the same error as before.

I delete all these widgets, also delete all the stuff in iCloud and made a force restart.

After this the COVID Trend Widget is not installable. I click on the blue Install button in ScriptDude, nothing happens.

I install via URL:
Code
https://scriptdu.de/?name=COVID%20Trend%20Widget&source=https://github.com/mvan231/Scriptable/blob/main/COVID%20Trend%20Widget/COVID%20Trend%20Widget.js&docs=https://github.com/mvan231/Scriptable/tree/main/COVID%20Trend%20Widget#generator

Doc
https://github.com/mvan231/Scriptable/tree/main/COVID%20Trend%20Widget

Country
Denmark

I get an error: Error in line 5: SyntaxError: Unexpected token ‘<‘

I’m close to give up.

—

**Comment by mvan231** [comment]
That error is confusing. I'm not sure what Script Dude might be doing but you should install the script directly from my GitHub repo by copy and paste or by using supermamon's "import script" script, which I have linked on my repo page of helpful scripts. 

I'm surprised you are facing an error on line 5 though because line 5 is all comments

**Comment by permaMonk** [comment]
UNBELIEVABLE. It works. I copied the whole code from the COVID Trend Widget site, make a new empty Script under Scriptable, paste the code. Open the the stack in widgets, add a new Scriptable widget, edit which one and country (with big starting letter) and it works. All 4 counties. 

Jeez! What a bloody way. 😭

Thx for your help. :)

—

**Comment by mvan231** [comment]
You are very welcome! I always recommend getting the script direct from the source. The import script code that supermamon made works great too but some strange things can happen when using ScriptDude apparently. Maybe they need to work on it?

anyway, I'll close this issue based on your successful feedback

**Comment by permaMonk** [comment]
Yes. Can be closed. :)
