### ISSUE TITLE
about week color

### ISSUE THREAD

**Issue by shelrock302** [mvan231/Scriptable#2]
Can you change the color differently on Saturday and Sunday?

**Comment by mvan231** [comment]
They could be changed to a different color, yes, but right now are set to use a different opacity instead.

**Comment by shelrock302** [comment]
oh I mean the colors to be different on Saturday and Sunday.
Would you please how can I change that?

**Comment by mvan231** [comment]
Can you be as specific as possible about this? I understand you want the color to be different vs just different opacity. But are you meaning Saturday has a different color than Monday - Friday and also Sunday has a different color? Or Saturday and Sunday are the same color but it should be different from M-F?

**Comment by shelrock302** [comment]
I am sorry for my poor English expression. I hope Saturday and Sunday and Weekdays are different colors. Ex) if M-F are white, Saturday is blue and Sunday is red.

**Comment by mvan231** [comment]
That's a very odd way to color a calendar but it is possible. I'm not sure why you'd want Saturday and Sunday to be a different color but I cannot into adding it in. The trouble is, it will require more options to be added. Let me see what I can come up with

**Comment by mvan231** [comment]
I have implemented this in the latest beta and will release it for the public release soon
