### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by permaMonk** [mvan231/Scriptable#21]
Even if I’m the last one using this widget I’m interested why ist not working anymore.

The error messeng is:
Error: Die Daten konnten nicht gelesen werden, da sie nicht das korrekte Format haben.
 [Error: The data could not be read because it is not in the correct format.]
 
So what’s the reason? It’s the end? Delete it?

**Comment by mvan231** [comment]
I can't really know which specific widget you're talking about. Can you let me know which one gave you the error?

**Comment by permaMonk** [comment]
[COVID Trend Widget](https://github.com/mvan231/Scriptable/tree/main/COVID%20Trend%20Widget)

**Comment by mvan231** [comment]
I took a look into this and it seems like the API I was using has been taken down or at least isn't working right now. Has this stopped working some time ago?

**Comment by permaMonk** [comment]
Yes it was fine 1 or 2 day before my first post.

**Comment by mvan231** [comment]
Seems the api owner needs to fix it or maybe they intentionally shut it down. I searched for quite a while yesterday looking for a new source for the info but wasn't able to find one with current data

**Comment by permaMonk** [comment]
Thx a lot for your effort. I have, as yourself, not much hope this could be fixed.

Which API have you used so far? Is there a contact person at this institution? If desired, I can be assistant, e.g. with inquiries in native German.

**Comment by mvan231** [comment]
I found out the heroku site/api was shut down and that is the reason why
this stopped working. I tried a few different APIs but they didn't look to
be promising due to the latest data being over a year old already and many
others that were shutdown for some reason or another

**Comment by permaMonk** [comment]
Uncomprehending: unfortunately, that sounds like COVID-19 is over because no more data is being collected. 🙄

**Comment by mvan231** [comment]
Absolutely agree with you. It's weird that the data for this seems to be more difficult to gather now. On Dec 10, 2022, at 05:28, permaMonk ***@***.***> wrote:﻿
Uncomprehending: unfortunately, that sounds like COVID-19 is over because no more data is being collected. 🙄

**Comment by permaMonk** [comment]
Do you know which institution put the API in at heroku site or who is the source of the API?

**Comment by mvan231** [comment]
I don't unfortunately. I had done some significant amount of searching and
ended up giving up because it became too complicated to find a solution to
the issue. I'd be happy to implement a new source for the info if you find
one though
