### ISSUE TITLE
Put overline above some entries

### ISSUE THREAD

**Issue by tarrkid** [mvan231/Scriptable#22]
Hi, I found your widget script and made a few tweaks (that probably no one would like!) to make a hyper-dense presentation. The one thing I would like to add would be an overline on the entries that include the day. The overline would help visually separate the days. Do you know how I might accomplish that? I’m an old school and out of practice programmer who has never touched javascript, so it was about all I could do to adapt your script to make this version. Any help is appreciated!
![56F09276-A8AC-498A-90A4-A01E5572AC56](https://user-images.githubusercontent.com/32531789/217145111-cb6efd64-0381-4c12-aefb-355679b6148f.jpeg)

**Comment by mvan231** [comment]
Which script did you modify? Of course one of the calendar scripts but which one specifically? You'd need to either make a separator line in draw context and add it as an image within a stack, or use a stack border to draw the line on the widget

**Comment by tarrkid** [comment]
I modified Upcoming Calendar Widget.

**Comment by mvan231** [comment]
Apologies I lost track of this issue. Are you still using the widget?

**Comment by tarrkid** [comment]
I'm still using a heavily-modified version of it; I've managed to solve the above issue myself. Thanks for checking back, but I'm good!

**Comment by mvan231** [comment]
Sounds good, I'll close the issue. Glad you're still using the widget and enjoying it. It's a fun app to tinker with for making useful and fun widgets
