### ISSUE TITLE
OpenWeather 2.5 is deprecated, 3.0 required

### ISSUE THREAD

**Issue by robertandrews** [mvan231/Scriptable#24]
https://github.com/mvan231/Scriptable/blob/fe57ab39ab9b47bbe2a0366df7b5d9b380f8e171/Weather%20Overview/Weather%20Overview.js#L196

Today, OpenWeather emailed me to say:

> We would like to inform you about our plans to complete the migration from One Call 2.5 to One Call 3.0 that started 2 years ago. In line with this, access to One Call 2.5 will be finally closed in June 2024. 
> 
> One Call 3.0 provides you with significantly advanced business-demanded features such as a minute forecast for 1 hour, 4 days forecast for any timestamp, a daily forecast for 8 days, including a human-readable summary, historical data (45-year archive) for timestamps, and with daily aggregation, 1.5-year long-term forecast with daily aggregation, and others.
> 
>  Click here for One Call 3.0 migration guide
>  One Call 3.0 is free 1,000 calls/day
> 
>  One Call 3.0 offers a flexible monthly subscription with a ‘pay-as-you-call’ scheme. You have 1,000 calls/day for free and pay only £0.0012 for each additional call.
>  
>  One Call 3.0 for business
> 
>  For demanded projects, we provide custom One Call 3.0 packages, tailored to your specific needs. These can include a certain volume of calls per month at a fixed monthly price, an OpenWeather end-user license (as opposed to an open CC license applicable by default), SLAs, and premium support options.

https://openweathermap.org/one-call-transfer

**Comment by mvan231** [comment]
Thank you for notifying. I know a number of people have updated their script manually to account for this. I've been meaning to update the code for it as well and have wanted to migrate the settings to be hardcoded in the script too because iCloud offloads the Scriptable .json files too frequently for my liking. 

What are your thoughts? 

Apologies for the long delay, I've been away from GitHub for quite a while as you can tell

**Comment by ParoTheParrot** [comment]
any advice for migration tin 3.0? @mvan231 ?

**Comment by mvan231** [comment]
> any advice for migration tin 3.0? @mvan231 ?

I thought I had updated the version on the server but I guess not. I'll push one now
