### ISSUE TITLE
Problem and features request

### ISSUE THREAD

**Issue by Yumega** [mvan231/Scriptable#3]
Firstly,Thanks for your contribution of the codes.

 Problem I met:
it works very well if I don't set photos as background,but when I set the background with a photo sliced by the no background js, everything was good on setting and I could see the widget display result on the final setting step,but on the screen it tells Alerts are not supported in a widget.

![6CB951B7-FD62-498E-9552-E83C3407C574](https://user-images.githubusercontent.com/61570667/103762083-b0e0e080-5052-11eb-888a-51e58f0c4f5f.jpeg)

Feature request:
The widget looks better if the words color can change into white above the photo background. Like the below ones,it seems that there is a transparent layer between the words and photo, they look nice.

![5FF71E9B-FE29-4E83-BDBF-6B1AFFA7206C](https://user-images.githubusercontent.com/61570667/103762132-be966600-5052-11eb-9609-55b63c5b8476.jpeg).

Thanks.

**Comment by mvan231** [comment]
For the first bit, the alert is the popup you see during setup. I'm working through some things to make the code more efficient right now actually. But when the widget refreshes that should go away. 

As for the font color, what color are you thinking it should be? The images you shared are interesting but I'm not sure what you're meaning to have me change

Also, I assume this is for the calendar widget. Is that correct?

If you have any modifications you've made, you can kindly submit a pull request and I'll review it

**Comment by Yumega** [comment]
I hope the color of all the fonts is white as the fonts on the photo I shared

**Comment by mvan231** [comment]
You want all of the font colors to be white? 

I have made the ability to use the calendar color as the event name color or not but the font color is still dependent on dark/light mode.  Maybe you can show an actual example of the widget and how you'd like to see it. Or you could try modifying it and send me a pull request with the info. 

Looking forward to your feedback

**Comment by mvan231** [comment]
I think you can check v1.5 that I just released and it might be exactly what you were looking for

**Comment by sleepyhellow** [comment]
Hi,
would it be possible to make this as a large widget?

**Comment by mvan231** [comment]
> Hi,
> would it be possible to make this as a large widget?

Are you still talking about the Calendar Indicator widget?

**Comment by sleepyhellow** [comment]
No, I‘m talking about the events you can see. Sorry that was not clear to understand. Would be nice to see the events of the next view weeks (i. e. 14 days). 
![84B33D3C-97EE-43B2-8E34-CDBBFE4DE2D4](https://user-images.githubusercontent.com/74114869/104870444-d3270800-5948-11eb-95be-aebde158c158.jpeg)

**Comment by mvan231** [comment]
> No, I‘m talking about the events you can see. Sorry that was not clear to understand. Would be nice to see the events of the next view weeks (i. e. 14 days).
> ![84B33D3C-97EE-43B2-8E34-CDBBFE4DE2D4](https://user-images.githubusercontent.com/74114869/104870444-d3270800-5948-11eb-95be-aebde158c158.jpeg)

The answer to my question then is, yes, not, no. 

You're looking to have additional functionality for a large size widget added. That view looks interesting. I'll see what I can do

**Comment by sleepyhellow** [comment]
Thanks.

**Comment by mvan231** [comment]
> I hope the color of all the fonts is white as the fonts on the photo I shared

Did you find the latest version to be what you were looking for?

**Comment by mvan231** [comment]
Based on the new improvements that have been added in 1.5 and 1.6 I'm going to close this

**Comment by mvan231** [comment]
> No, I‘m talking about the events you can see. Sorry that was not clear to understand. Would be nice to see the events of the next view weeks (i. e. 14 days).
> ![84B33D3C-97EE-43B2-8E34-CDBBFE4DE2D4](https://user-images.githubusercontent.com/74114869/104870444-d3270800-5948-11eb-95be-aebde158c158.jpeg)

@sleepyhellow i couldn't find a good way to get in touch with you, but would you want to beta test the new large widget size feature?
