### ISSUE TITLE
Store set-up settings between updates

### ISSUE THREAD

**Issue by himynamesned** [mvan231/Scriptable#6]
Is there a way of storing the menu settings between updates, so the whole menu doesn't have to be reran between each update? I have seen settings stored in iCloud or Reminders app for example for shortcuts.

Running the whole menu between each update is a bit annoying. Even if the menu could astrix current setting whilst running, would be a big help - for example (yes*/no) meaning yes was selected last time. Meaning the same options could quickly be selected when running the setup. Any new options wouldn't have an astrix so the question could be read thoroughly before selecting an option. 

Also making "update" standing out on the widget would be beneficial. Maybe in red/yellow to stand out.

Great work on the updates! My most-frequently used widget by far!

**Comment by mvan231** [comment]
Thanks for using the widget! Which widget is this for? I'm guessing it's the Upcoming Calendar Indicator widget, yes?

If so, then the settings file is stored already but maybe you're talking about something else?
