### ISSUE TITLE
Line below day names

### ISSUE THREAD

**Issue by deta362** [mvan231/Scriptable#7]
Hi,

Great widget! In the calendar section, is it possible to add a line between the day and dates, something similar to this: 
![9EFCBA3C-696D-4C99-A121-D2ACBCA134CB](https://user-images.githubusercontent.com/72606495/107549701-0ebf9580-6bc8-11eb-8a28-128294b3064d.jpeg)

**Comment by mvan231** [comment]
It should be possible. Let me look into it to see what I can come up with

**Comment by mvan231** [comment]
Hi again, I looked into this and came up with this:
![6EC4F264-B186-4ED5-BA23-5E6F881DBC0D](https://user-images.githubusercontent.com/50910610/107623899-0ac36000-6c28-11eb-8e9d-0848b92df3ed.jpeg)

let me know what you think. The color of the line is dependent on the baseText color

**Comment by deta362** [comment]
Yes that’s great!

**Comment by mvan231** [comment]
Perfect! I'll push out the update including this soon. Expect to see it in 1.8 along with some new method I just implemented for new settings not having to fully setup all of the settings when a new feature is added.
