### ISSUE TITLE
Suggestion for Upcoming Calendar Widget

### ISSUE THREAD

**Issue by MajorTomDE** [mvan231/Scriptable#8]
Hey,

since one of my favorite apps "Agenda+" is no longer being developed, I have a little great feature suggestion:

Hide Calendar and only show upcoming events in this way:

![image](https://user-images.githubusercontent.com/76742790/107887147-4306bf00-6f04-11eb-8045-a9a0f2c3bfa8.jpeg)

**Comment by mvan231** [comment]
Is this for Upcoming Calendar Indicator or I suppose it could be more for the Upcoming Calendar Widget itself. 

I do wonder, what happens if the given day has more than just one event?

**Comment by MajorTomDE** [comment]
Sorry, of course it is for "Upcoming Calendar Events Widget". 
I like the way the appointments are displayed in a large widget.
If a day has more than on event, you will see it in the list. The second event without the data-value.

**Comment by mvan231** [comment]
Interesting for sure. Even in medium widget you will see multiple events for a given day and the proceeding days

**Comment by MajorTomDE** [comment]
Yes, thats OK. But for me the large widge is most important. Especially on the iPad. Then you always have all upcoming events in view on the left side.

**Comment by mvan231** [comment]
I didn't think there were widgets on iPad. But I see your point for sure. I'll get to work on this. Sorry for the delay.  Things have just been really busy for me with work and life

**Comment by mvan231** [comment]
Just so it's clear, do you have an image of what you are meaning if there are more appointments on the same day?

**Comment by mvan231** [comment]
Something like this? 
![511C5C77-FB06-4C9E-A9E2-7165C44B38CB](https://user-images.githubusercontent.com/50910610/110713141-6523f200-81cf-11eb-8809-5f3e831602e9.jpeg)

**Comment by MajorTomDE** [comment]
Hey @mvan231 
really cool. That's how I imagined it.
Thank you very much for the great work 😉😎👍

**Comment by mvan231** [comment]
Glad it was understood well. So would the right side just be blank like that then?

**Comment by MajorTomDE** [comment]
For me it's OK. It depends on the final font size and the length of the event title.
In other widgets the event title will be truncated.
e.g.
Birthday from Maximilian Mustermann
--> Birthday from Maxim...

Other question: Is it possible to select the calendars who will displayed in the widget?
At the moment I have two birthday calendars in the calendar selection screen: iOS standard and from Outlook. One is enough ;-)

**Comment by mvan231** [comment]
> Other question: Is it possible to select the calendars who will displayed in the widget?
At the moment I have two birthday calendars in the calendar selection screen: iOS standard and from Outlook. One is enough ;-)

Yes it definitely is possible to have a calendar selection. As I was building the latest version of this Upcoming Calendar Widget, I realized that I didn't have a calendar selection included like I do in Upcoming Calendar Indicator.

**Comment by mvan231** [comment]
I have updated the code and placed a version available for you to try. 

https://github.com/mvan231/Scriptable/blob/main/Upcoming%20Calendar%20Agenda.js

This has transparency as an option if you have it enabled (base code defaults to true). 
You need the no-background.js from supermamon for that part to work

**Comment by MajorTomDE** [comment]
Wow ... the first version look really good. Thank you for the great work :-)

While testing, I noticed the following:

- With german language I only see the Month + Weekday, but not the day as "number"
- I use outlook.com as calendar. outlook.com has its own birthday calendar called "Geburtstage" on german. Also the build in iOS birthday calendar is called "Geburtstage". Although I have selected only one, I see booth because in settings.json only "Geburtstage" is saved. You can see it in the example "Geburtstag von Armin" and "Armin (6. Geburtstag)
- Is it possible to display appointments over several days? Example: I have 5 days of vacation (Urlaub). But I only see the first day.
- Slightly increase the margin at the top and bottom.

![test1](https://user-images.githubusercontent.com/76742790/111591784-2fcb6580-87c8-11eb-8dd7-8d768f9e2fdb.png)

**Comment by mvan231** [comment]
> * With german language I only see the Month + Weekday, but not the day as "number"

This is interesting, the shortened version of the month name must be longer than what it is in English (3 characters usually). Would just having it display in the locale numeric display suffice?

> * Although I have selected only one, I see booth because in settings.json only "Geburtstage" is saved. You can see it in the example "Geburtstag von Armin" and "Armin (6. Geburtstag)

Yes I have come into this as well with Birthdays being in my Google and iCloud calendars. Holidays are the same too. I have been considering changing to using the Calendar ID instead of the name, it'll just make the settings file look a bit more strange, but should be okay.



> * Is it possible to display appointments over several days? Example: I have 5 days of vacation (Urlaub). But I only see the first day.

When you say it is 5 days of vacation, is it a single 5 day long appointment or 5 recurring appointments? If it is the later, then it should display, but if it is the former, then that is why it isn't displaying like you would think



> * Slightly increase the margin at the top and bottom.

I can't really tell for sure in your screenshot, but it looks like you are showing this in the app instead of in a widget. The display in the app typically looks different than the display in the widget. Maybe try it as a widget and see how it looks. The margin could be increased by adding padding or by allowing one fewer event to be displayed

**Comment by mvan231** [comment]
Did you have any further feedback on this?

**Comment by mvan231** [comment]
After having possibly used this for a while, what are your thoughts on it? Should I release it as another widget?

**Comment by mvan231** [comment]
I'm just curious about this one still. Are you still using the widget? Is it having any issues?
