### ISSUE TITLE
url error

### ISSUE THREAD

**Issue by felho001** [mvan231/Scriptable#9]
I set my country Hungary and if I test scribptable app run all good but if I set widget I choose script and paramater Hungary widget say this.
![IMG_1828](https://user-images.githubusercontent.com/45117257/108281521-31c9e680-7180-11eb-9334-74ee7cbd2b48.jpg)
![IMG_1827](https://user-images.githubusercontent.com/45117257/108281526-3393aa00-7180-11eb-924c-ccfcb3aadd5c.jpg)

**Comment by mvan231** [comment]
How did you get it working in the app? If you changed the default to be Hungary then no need to use the widget parameter 

seems you found a fix already?

**Comment by felho001** [comment]
Yes i fix I copy country name the webpage and past parameter and now work. If I widget live blank not work

**Comment by felho001** [comment]
it is possible for the widget to show all the data? Like this 
Hungary
Cases: 391,170 | Today: 1,548 | Active: 77,250
Deaths: 13,931 | Today: 94
Recovered: 299,989 | Critical 321

not only total?

**Comment by mvan231** [comment]
Of course! The today information is often 0 though so I left it out

**Comment by felho001** [comment]
> Of course! The today information is often 0 though so I left it out

and how?

**Comment by mvan231** [comment]
There would need to be adjustments made to do this. At the very beginning you can see where it is initializing the variables. We would need to setup variables for those other items then simply use the addItem function call to add them to the widget :)
